Update docs and fix dpkg scripts [skip ci]

diff --git a/pkg/debian/preinst b/pkg/debian/preinst
--- a/pkg/debian/preinst
+++ b/pkg/debian/preinst
@@ -2,19 +2,22 @@
 
 SKY_DIR=/var/lib/skytable
 
-# create the data directory
-if [ ! -e $SKY_DIR ]; then
-    mkdir $SKY_DIR
-elif [ ! -d $SKY_DIR ]; then
-    echo "ERROR: /var/lib/skytable exists but it is not a directory" 1>&2
-    return 1
+# Create the data directory if it doesn't exist
+if [ ! -e "$SKY_DIR" ]; then
+    mkdir -p "$SKY_DIR"
+    echo "Created directory $SKY_DIR"
+elif [ ! -d "$SKY_DIR" ]; then
+    echo "ERROR: $SKY_DIR exists but it is not a directory" 1>&2
+    exit 1
 fi
 
-if [ $1 = "install" ]; then
-    # add the `skytable` user
-    adduser --system --group skytable
-    # change ownership
-    chown skytable:skytable /var/lib/skytable
+# On initial install, add the `skytable` user
+if [ "$1" = "install" ]; then
+    echo "Creating user 'skytable'"
+    if ! getent passwd skytable > /dev/null; then
+        adduser --system --group --no-create-home skytable
+    fi
+    chown -R skytable:skytable "$SKY_DIR"
+    echo "Created user 'skytable'"
 fi
-
 #DEBHELPER#
